### ISSUE TITLE
Features and test cases checklist

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocol2#11]
## Features:
- [X] Parameter serialization/deserialization
- [x] public library for third-party contract 
- [X] Multiple rings submission
- [X] Order broker
- [X] On-chain order book
- [x] Token registry factory/agency
- [X] Javascript simulation library
- [X] multiple signature support
- [x] EIP 712 implementation
- [x] ~~Interception~~
- [x] drop both TokenRegistry and Name registry entirely
- New fee model
  - [x] only income tax/no consumer tax
  - [x]  four level of tax rates and burn LRC to lower burn rates
  - [x] Allow users to lock LRC to get lower burn rates
  - [x] Support Lock up LRC for refund (discount on fee burn)

## Test cases:
- [X] parameter serialization/deserialization
- [X] Exchange: rings submission:
    - [X] multiple rings
    - [X] multiple rings, one is invalid
    - [X] 2-order ring, prices matched exactly
    - [X] 2-order ring, with price gap
    - [x] 2-order ring, partial fill
    - [x] 2-order ring, one order has been partially filled before
    - [x] 2-order ring, insufficient token balance
    - [x] 2-order ring, insufficient approve amount
    - [x] 2-order ring, insufficient fee token balance
    - [x] 2-order ring, buy LRC, pay LRC as fee, insufficient LRC balance
    - [x] 2-order ring, sell LRC, pay LRC as fee, LRC balance < fillAmouont + feeAmount
    - [x] 2-order ring, pay other token as fee
    - [x] 2-order ring, allOrNone is true
    - [x] 3-order ring, prices matched exactly
    - [x] 3-order ring, with price gap
    - [X] 2-order ring, one order is invalid
- [X] Exchange: cancel order
    - [X] cancel single order
    - [X] cancel orders with a specific trading pair for a address
    - [X] cancel all orders for a address before a timestamp
- [X] Exchange: broker
- [x] support EIP 712
- [x] ~~Token registry~~
- [X] Trade Delegate
- [x] Orderbook: on-chain order book
